[package]
name = "fs_usage_summary"
version = "0.1.0"
authors = ["john li <jli@circularly.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
lazy_static = "1"
regex = "1"
structopt = "0.3.20"
